// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AwsExports = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:acc66bf0-e047-4c79-8849-bb45808e81e7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bi0Nmx0V0",
    "aws_user_pools_web_client_id": "24qko6m7oco27pcofi6dg1r6m9",
    "oauth": {
        "domain": "regraphers.auth.us-east-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "aws.cognito.signin.user.admin",
            "profile"
        ],
        "redirectSignIn": "https://google.com/",
        "redirectSignOut": "https://google.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://qzfysucpyjfvzeogqa26riqyu4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "regraphers",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default AwsExports;