[build]
  Command = "yarn build && yarn build:lambda"
  Functions = "lambda"
  Publish = "build"
[context.production]
  Command = "yarn schema:start-and-publish && yarn build && yarn build:lambda"
[context.deploy-preview]
  Command = "yarn schema:start-and-check && yarn build && yarn build:lambda"